spring:
  datasource:
    url: jdbc:postgresql://ordermanagerdb.cp6smok6gzvy.eu-central-1.rds.amazonaws.com:5432/postgres
    username: masteruser
    password: ordermanagermaster1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: Malcon1243373
#    key-store-type: PKCS12
#    key-alias: myalias


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false

